services:
  webhooks.api:
    image: webhooks.api
    build:
      context: .
      dockerfile: Webhooks.Api/Dockerfile
    environment:
      # Web App Env
      - ASPNETCORE_ENVIRONMENT=Docker
      # Postgres Connection
      - ConnectionStrings__PostgresConnection=Host=webhooks.db;Database=WebhooksDb;Username=postgres;Password=postgres
      # RabbitMQ Connection
      - RabbitMQ__Host=amqp://webhooks.mq:5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      # OpenTelemetry 
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://webhooks.aspire-dashboard:18889
    depends_on:
      - webhooks.db 
      - webhooks.mq
    ports: 
      - "8080:8080"
      - "7144:7144"
      
  webhooks.db:
    image: postgres:latest
    hostname: webhooks.db
    environment:
      POSTGRES_DB: WebhooksDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "54320:5432" # Changed port to avoid conflict with local postgres
      
  webhooks.seq:
    image: datalust/seq:latest
    container_name: webhooks.seq
    volumes:
      - ./.containers/seq:/data
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5431:5431
      - 8081:80

  webhooks.mq:
    image: rabbitmq:3-management
    container_name: webhooks.mq
    hostname: webhooks.mq
    volumes:
      - ./.containers/queue:/var/lib/rabbitmq
      - ./.containers/queue:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  webhooks.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
      - 4317:18889