CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'webhooks') THEN
        CREATE SCHEMA webhooks;
    END IF;
END $EF$;

CREATE TABLE webhooks.subscriptions (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WebhookUrl" text NOT NULL,
    "EventType" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_subscriptions" PRIMARY KEY ("Id")
);

CREATE TABLE webhooks.delivery_attempts (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WebhookSubscriptionId" bigint NOT NULL,
    "Payload" text NOT NULL,
    "ReponseStatusCode" integer,
    "Success" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_delivery_attempts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_delivery_attempts_subscriptions_WebhookSubscriptionId" FOREIGN KEY ("WebhookSubscriptionId") REFERENCES webhooks.subscriptions ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_delivery_attempts_WebhookSubscriptionId" ON webhooks.delivery_attempts ("WebhookSubscriptionId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251103113040_CreateDb', '9.0.10');

COMMIT;

